server:
  port: 8080
  baseURL: "/opt/filebrowser/masso"
  database: ./database.db
  sources:
  - path: /opt/filebrowser/masso
    name: "MASSO Files"
    config:
#      disableIndexing: true
      defaultUserScope: "/"
#  permissions:
#    api: true
#    admin: false
#    modify: true
#    share: false
#    realtime: true
#    delete: true
#    create: true
#    download: true
#  - path: /opt/filebrowser/test/
#    name: "testing"
#    config:
#        defaultEnabled: true
#        defaultUserScope: "/opt/filebrowser/test"
  logging:
  - levels: info|warning|error|debug
    apiLevels: info|warning|error|debug
    output: /opt/filebrowser/logs
    noColors: false
    utc: false
  cacheDir: /opt/filebrowser/tmp
frontend:
  name: FileBrowser Quantum
  externalLinks:
    - text: "Detach"
      title: "Unmount USB"
      url: "http://10.0.0.128:8090/detach?close=1"
    - text: "Commit"
      title: "Sync to USB"
      url: "http://10.0.0.128:8090/commit?close=1"
    - text: "Attach"
      title: "Re-mount USB"
      url: "http://10.0.0.128:8090/attach?close=1"
auth:
  adminUsername: admin
  adminPassword: admin
  methods:
    password:
      minLength: 4
userDefaults:
  permissions:
    api: true
    admin: false
    modify: true
    share: true
    realtime: true
    delete: true
    create: true
    download: true
